### ISSUE TITLE
Code review for com.rexuiz.main.Runner.java

### ISSUE THREAD

**Issue by ghost** [kasymovga/RexuizLauncher#1]
1. Не понятно почему наследован от `com.rexuiz.main.Fetcher.java`
2. Метод `checkUpdate()` выполняет не то, что от него ожидается, в нем изменяются свойства класса, хотя с первого взгляда это никак не понятно. Метод надо разбить на более конкретные, а затем уже их вызывать.
3. Необходимо обрабатывать конкретные исключения, не должно быть такого:
   `catch (Exception ex) {
           }`
   Лучше добавить логгер для класса или для всего приложения.
4. В коде не желательно использовать имена свойств как:
   `if (osArch.contains("64")) {`, `if (osName.contains("win")) {`, `System.getProperty("os.name")` и т.д., необходимо их вынести в константы класса.
5. Зачем?

```
int i, n;
        for (i = 0; i < 100; i++) {
            if (properties.getProperty("launcher.url" + Integer.toString(i), "") == "")
                break;
        }
        if (i == 0) {
            syncURLs = AppConstants.syncURLs;
        } else {
            n = i;
            syncURLs = new String[n];
            for (i = 0; i < n; i++) {
                syncURLs[i] = properties.getProperty("launcher.url" + Integer.toString(i));
            }
} 
```

**Comment by kasymovga** [comment]
ну, huyak huyak production.

**Comment by kasymovga** [comment]
Я быдлокодер, мне можно)
